### ISSUE TITLE
Enable Travis for this repo

### ISSUE THREAD

**Issue by fabianmoronzirfas** [ixds/ws-broadcast#11]
@martenbiehl or @jperals I'm not a admin for this org but would love to enable travis-ci for at least this repo for automated test. https://docs.travis-ci.com/user/tutorial/ I would need owner rights or some owner needs to enable travis for me.

🍻

**Comment by jperals** [comment]
Hi @fabianmoronzirfas! Sorry this took a bit long, I was out of town and just came back. Travis should be configured now for this repo, can you confirm? (I completed up to step 3 in https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci)

**Comment by fabianmoronzirfas** [comment]
Looks like it. I will test this soon(-ish).

Thank you.

**Comment by fabianmoronzirfas** [comment]
Travis is working. Thanks 

[![Build Status](https://travis-ci.org/ixds/ws-broadcast.svg?branch=master)](https://travis-ci.org/ixds/ws-broadcast)
